# g-openwebui Dockerfile (naked scaffold)
FROM ghcr.io/open-webui/open-webui:main
# TODO: configure volumes, ports (planned exposure: 8080)
# TODO: connect authentication and storage layers once Wardrobe overlays exist
