# g-ollama Dockerfile (naked scaffold)
FROM docker.io/ollama/ollama@sha256:bef60d0ca6194ae88df3107cd0f53cc44cc2d0e3d1a6d9798bab9ef80e31e364
# TODO: configure volumes, ports (planned exposure: 11434)
# TODO: align environment variables with forthcoming fundament scripts
